#
# see https://blog.logrocket.com/containerized-development-nestjs-docker/
#
# explore running docker filesystem with
#   docker-compose exec main sh
#
version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile-main
      target: development
    volumes:
      - ./srvs/main:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${MAIN_PORT}:${MAIN_PORT}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - loginapi
      - redis
  loginapi:
    container_name: loginapi
    build:
      context: .
      dockerfile: Dockerfile-loginapi
      target: development
    volumes:
      - ./srvs/login-api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${LOGIN_PORT}:${LOGIN_PORT}
      - 9230:9230
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
networks:
  webnet:
