#
# see https://blog.logrocket.com/containerized-development-nestjs-docker/
#
FROM node:12.13-alpine As development

WORKDIR /usr/src/app

COPY ./srvs/main/package*.json ./

RUN npm install --only=development

COPY ./srvs/main .

RUN npm run build

FROM node:12.13-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY ./srvs/main/package*.json ./

RUN npm install --only=production

COPY ./srvs/main .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]