#
# see https://blog.logrocket.com/containerized-development-nestjs-docker/
#
# explore running docker filesystem with
#   docker-compose exec main sh
#
version: '3.7'

services:
  mainsite:
    container_name: mainsite
    build:
      context: ./main-site
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./main-site:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${MAIN_PORT}:${MAIN_PORT}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env-main-site
    networks:
      - webnet
    depends_on:
      - authapi
      - demoapi
      - redis
  authapi:
    container_name: authapi
    build:
      context: ./auth-api
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./auth-api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
      - 9230:9230
    command: npm run start:debug
    env_file:
      - .env-auth-api
    networks:
      - webnet
  demoapi:
    container_name: demoapi
    build:
      context: ./demo-api
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./demo-api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${DEMO_PORT}:${DEMO_PORT}
      - 9231:9231
    command: npm run start:debug
    env_file:
      - .env-demo-api
    networks:
      - webnet
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
networks:
  webnet:
